### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by mmbarness** [advantic-au/libmqm-sys#4]
First of all, I've been looking for a current implementation of this for a while now and I'm super excited you've started building one. And although this kind of low-level work and rust/c interop isn't something I'm familiar with, I want to learn more. Trying to get your example working and having an issue:

<img width="711" alt="image" src="https://github.com/advantic-au/libmqm-sys/assets/80414315/c97a8b51-6c22-4b21-b5fc-cb12847d3582">

The error I get in particular is as follows:
```
mismatched types
expected raw pointer `*mut i8`
   found raw pointer `*mut [i8; 48]
```

I'm on rust 1.79 nightly, Ubuntu 22, and IBM MQ 9.3.5.0

Thanks again, really excited about this.

**Comment by spitsw** [comment]
The example was put together in haste. I would preferably have a full example that connects, puts, gets, and then disconnects. I will update the example.

Using the crate directly to build a product or utility will have a rough developer experience as it exposes the unsafe functions of the MQI library without any of the benefits of safety guarantees, and native rust types.

In parallel I'm developing an idiomatic rust library that uses this crate which is not currently open sourced.

**Comment by mmbarness** [comment]
Gotcha, makes sense. Yeah, bindings like these are what I've been looking for since I realized there is no rust library for interacting with IBM MQ, which is a blocker for any hopes I have of getting rust-based services greenlit at work. I've written a lot of rust in personal projects and I'd be super interested in making contributions to yours, but it'd very much be a learning experience for me. Unsafe logic isn't something I've worked with much yet.

**Comment by spitsw** [comment]
@mmbarness your offer of contribution is welcome. Learning never ends.

This crate is very much feature complete. All MQI and MQAI functions have been exposed. Any changes will be done mostly to support the idiomatic API.

I plan to upload some code of the idiomatic API in another repo shortly. The majority of the unsafe wrapping has been done in this library, but there is plenty of work to be done to make it usable. You are certainly invited to contribute whether it be just using the library and providing critical feedback, asking questions, contributing code and documentation, adding examples or raising issues.
